### ISSUE TITLE
Como vai ser a tela inicial do jogo?

### ISSUE THREAD

**Issue by azevgabriel** [azevgabriel/educacao_especial#13]
### Principais questões

Como vai ser o Design?
O aluno vai ter algum tipo de login?

### Questões secundárias

**Se o aluno tiver um acompanhamento, com sua página personalizada.**
1. Vamos acompanhar a taxa de acertos do aluno pela plataforma?
2. Vamos tentar verificar o temor essencial pelo cursor do mouse? 
3. Vamos ter um progresso de aluno?

**Comment by leoalmelin** [comment]
Não estava pensando nesse login e acompanhamento individual, mas é um caminho interessante. Com isso poderíamos ter um cadastro diferenciado para os tutores que permitice acompanhar o progresso de todos os alunos. Isso precisaria ser implementado agora? Se não, acho melhor focarmos no desenvolvimento das três primeiras lições. Depois podemos elaborar um projeto focado nisso e receber o feedback de educadores para separarmos quais pontos são mais interessantes para termos o controle.

**Comment by leoalmelin** [comment]
Sobre o Design:

1. Os educadores poderão adicionar palavras e imagens ao jogo?
2. Todos os jogos seguirão a temática de fazenda, ou iremos também adicionar outros elementos? Se forem existir outros temas preciso elaborar algo mais generalizado.
3. Futuramente iremos dividir os jogos em categorias? Ou deixaremos todos os jogos distribuídos de forma geral?

**Comment by azevgabriel** [comment]
> Não estava pensando nesse login e acompanhamento individual, mas é um caminho interessante. Com isso poderíamos ter um cadastro diferenciado para os tutores que permitice acompanhar o progresso de todos os alunos. Isso precisaria ser implementado agora? Se não, acho melhor focarmos no desenvolvimento das três primeiras lições. Depois podemos elaborar um projeto focado nisso e receber o feedback de educadores para separarmos quais pontos são mais interessantes para termos o controle.

Não precisa ser implementado agora, mas vamos colocar deixar de plano secundário após fazermos o MVP. O que precisamos na realidade, é de uma tela para a gente colocar o três tipos de jogos. Tipo um hall de jogos.

**Comment by azevgabriel** [comment]
> Sobre o Design:
> 
> 1. Os educadores poderão adicionar palavras e imagens ao jogo?
> 2. Todos os jogos seguirão a temática de fazenda, ou iremos também adicionar outros elementos? Se forem existir outros temas preciso elaborar algo mais generalizado.
> 3. Futuramente iremos dividir os jogos em categorias? Ou deixaremos todos os jogos distribuídos de forma geral?

@leoalmelin Sobre a **primeira questão**, acho que é possível. No primeiro jogo, o educador só precisa adicionar o nome e as imagens. Mas ai custaria um preço no serviço de armazenamento da AWS. (Não seria escalável para meu bolso, rs). Acho que melhor que isso, é deixar uma caixa para sugestões de lista de palavras, e depois selecionar o que fizer sentido para nós. Até para não perder a ideia de design que criamos. Sobre a **segunda questão**, acho que a gente pode mudar a ambientação de acordo com o tema que as palavras estão relacionadas (já linkando com a terceira questão), então se fosse só palavras de algo relacionado à família teríamos um outro fundo e/ou outra ambientação. Mas no caso do menu/hall desses três jogos, a gente criaria uma ambientação divertida e colorida trazendo algo sobre escola ou aprendizado, que seria uma coisa mais genérica, porém me ajuda nessa ideia aqui, acho que podemos melhorar. **Terceira questão**, acho que poderíamos criar categorias, porque facilitaria novas ideias, como por exemplo introduzir a ideia de fazenda, com os jogos que a gente criou mais um conteúdo em texto ou em vídeo.

**Comment by leoalmelin** [comment]
@azevgabriel 
1. Concordo com você. Acredito que é melhor adicionar a caixa de sugestões.
2. Perfeito, irei pensar em algo mais geral para a versão com diferentes temas.
3. De acordo. Isso também facilitaria a customização dos menus.

**Comment by leoalmelin** [comment]
@azevgabriel Outro ponto importante, é de que as imagens que estamos usando são de domínio público, mas precisam ser referenciadas. Uma opção seria, depois que o jogo e estas ideias iniciais estejam mais avançadas, que busquemos alguém para recriar estes designs. 

Segue o que tinha pensado para usarmos como capa nesta primeira etapa, com o tema de fazenda.

![image](https://user-images.githubusercontent.com/106711003/172031302-92548268-22d9-4190-9241-2a2723ab7b91.png)

**Comment by azevgabriel** [comment]
@leoalmelin Massa! Estamos de acordo! A única coisa que temos que pensar então é como referenciar essas imagens, mas vou abrir outra issue para resolvermos isso! Sobre a questão da tela inicial já estamos fechados.

**Comment by leoalmelin** [comment]
@azevgabriel Ótimo. Apenas irei adicionar aqui as imagens com qualidade melhor.
![Capa](https://user-images.githubusercontent.com/106711003/172031947-16b08f7b-81e3-4f8e-95dc-bf2d4c030ef0.png)
![BotãoA](https://user-images.githubusercontent.com/106711003/172031948-4040b8b0-ac85-42d0-ae34-d3314b47278c.png)
![BotãoB](https://user-images.githubusercontent.com/106711003/172031949-d433f7f5-001d-4605-a309-43d44262a757.png)
![BotãoC](https://user-images.githubusercontent.com/106711003/172031951-1baa2164-68d4-4de2-830d-a27969c9e622.png)
