### ISSUE TITLE
Criação de tela inicial

### ISSUE THREAD

**Issue by leoalmelin** [azevgabriel/educacao_especial#21]

**Comment by leoalmelin** [comment]
Pensei nessa tela como base. Os quadrados de cada jogo podem estar dispostos em linha, com uma seta para avançar e recuar. Poderíamos também colocar um logo para o site.

**Comment by leoalmelin** [comment]
![Site](https://user-images.githubusercontent.com/106711003/178173538-b4520370-092e-41a5-ae2a-0ecdedd0895a.png)

**Comment by azevgabriel** [comment]
> resposta à @leoalmelin 

Leo, consegue me mandar só o fundo?

**Comment by leoalmelin** [comment]
![Site (1)](https://user-images.githubusercontent.com/106711003/179101658-cafca9bf-7e08-44a2-89f8-4b3b9fc4b0c7.png)

**Comment by leoalmelin** [comment]
![Site (2)](https://user-images.githubusercontent.com/106711003/179103803-02527760-96b2-475a-8dcf-4fca85701983.png)
