### ISSUE TITLE
O que vamos fazer quando todas as letras forem acertadas na Lesson One.

### ISSUE THREAD

**Issue by azevgabriel** [azevgabriel/educacao_especial#5]
O que vamos fazer quando todos os as letras forem acertadas em um animal. Passamos pro próximo? Vai ter alguma pontuação? Vamos mostrar pro aluno que ele conseguiu?

O que fazer também quando o aluno finalizar todos os animais? Fazemos ele voltar para a tela inicial?

**Comment by leoalmelin** [comment]
1. (O que vamos fazer quando todos os as letras forem acertadas em um animal?) - Acho que somente avisar que está correto e abrir a opção de avançar ou voltar para o menu, como você colocou. É possível adicionar também efeitos de fogos de artifício? (Talvez podemos pensar em uma comemoração com os animais tbm)
2.  (Vai ter alguma pontuação?) - Acho melhor não. Como os jogos são voltados para crianças com dificuldades especiais com foco na acessibilidade, talvez as discrepâncias de pontuação possam causar constrangimento nas crianças. O que você acha?
3.  (O que fazer também quando o aluno finalizar todos os animais?) - Voltar para a tela inicial parece a melhor opção.

**Comment by azevgabriel** [comment]
> Resposta à @leoalmelin 
>  Acho que somente avisar que está correto e abrir a opção de avançar ou voltar para o menu, como você colocou. É possível adicionar também efeitos de fogos de artifício? (Talvez podemos pensar em uma comemoração com os animais tbm)

Acho que é possível sim! Criar esse efeito. Tem que ser algo genérico para todos as categorias, acho que fogo de artificio seria bacana!

> Acho melhor não. Como os jogos são voltados para crianças com dificuldades especiais com foco na acessibilidade, talvez as discrepâncias de pontuação possam causar constrangimento nas crianças. O que você acha?

Concordo com você!

> Voltar para a tela inicial parece a melhor opção.

O que será a nossa tela inicial então? Dei a sugestão do hall de jogos, mas pode ser algo à mais. Tem alguma sugestão?
